### ISSUE TITLE
Command palette entry

### ISSUE THREAD

**Issue by orschiro** [sabhiram/sublime-clipboard-diff#1]
Dear @sabhiram,

Many thanks for this neat package!

I always keep forgetting about the keyboard shorcut.

Do you think it is possible to add a command palette entry `Clipboard Diff`?

Thankfully,

Robert

**Comment by sabhiram** [comment]
Oh sure thing. Let me look into how to do that, bit of a sublime newb.

**Comment by sabhiram** [comment]
@orschiro Ok so that is an awesome idea, and it should be super easy to add. Give me a few minutes :+1:

**Comment by sabhiram** [comment]
This release implements this awesome suggestion: https://github.com/sabhiram/sublime-clipboard-diff/releases/tag/1.1.3

I also added it to the Context Menu (when we right click on a text area).

Here is the commit which implements the same: https://github.com/sabhiram/sublime-clipboard-diff/commit/b8ad2e730b632c97626eccabdb3ac32e4cbb96c2

@orschiro Let me know if that works out, and thank you for taking the time to open an issue :)

**Comment by orschiro** [comment]
Perfect!

I would like to install it. Can you please deploy version 1.3 on https://packagecontrol.io/packages/Clipboard%20Diff

**Comment by sabhiram** [comment]
Yep it should have updated now. I think Package Control takes about 30 mins to re-scan and re-publish new versions.

**Comment by orschiro** [comment]
Cool, the command palette works perfectly. Thank you very much!

Robert

On 2015-02-09 23:56, Shaba Abhiram wrote:

> Yep it should have updated now. I think Package Control takes about 30 
> mins to re-scan and re-publish new versions.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/sabhiram/sublime-clipboard-diff/issues/1#issuecomment-73609127.

## 

not perfect | trying to live mindfully |
bad at planning | creative thinking |
nothing special | carpe diem | simple design

Co-Creator of @MindfulMeerkats
www.robert.orzanna.de
twitter.com/@orschiro
