### ISSUE TITLE
Show information about same text

### ISSUE THREAD

**Issue by funivan** [sabhiram/sublime-clipboard-diff#3]
Hello. Thanks for great plugin.
It will be cool to see some message like: "Text are same" or something like that. 

I install this plugin, copy text, select other text, then run clipboard diff And nothing happen. Just opened new empty tab "Clipboard diff". I don`t know if plugin works or not =)

**Comment by funivan** [comment]
ping

**Comment by sabhiram** [comment]
Heh, I have not visited this code in about 2 years. Its a decent idea and probably simple to implement. Want to send me a PR?

**Comment by sabhiram** [comment]
@funivan - Got bored and needed a change :)

Check out: https://github.com/sabhiram/sublime-clipboard-diff/releases/tag/1.1.4
